remote_theme: yaoyao-liu/minimal-light

title: Rabbia Hassan
position: Computer Vision Researcher
affiliation: null
email: rabbia.hassan@seecs.edu.pk

keywords: computer vision, 3D point clouds, deep learning, localization, remote sensing
description: Academic profile of Rabbia Hassan, featuring research, publications, projects, teaching, and academic achievements.
canonical: https://rabbia-hassan.github.io/

google_scholar: https://scholar.google.com/citations?user=trSrwpAAAAAJ&hl=en&oi=ao
cv_link: ./cv.pdf
github_link: https://github.com/Rabbia-Hassan
linkedin: https://www.linkedin.com/in/rabbia-hassan-309aa683
#twitter: null

avatar: ./profile.jpg
favicon: null
favicon_dark: null

enable_footnote: false
auto_dark_mode: true
font: "Sans Serif"
